# Generated by Django 6.0.5 on 2026-05-09 03:10

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, db_index=True, help_text='Preencha apenas para itens individualizados (armas, rádios). Deixe vazio para itens de lote (munição, fardamento).', max_length=100, null=True, verbose_name='Número de série')),
                ('tipo_material', models.CharField(choices=[('Armamento', 'Armamento'), ('Munição', 'Munição'), ('Colete Balístico', 'Colete Balístico'), ('Rádio HT', 'Rádio HT'), ('Viatura', 'Viatura'), ('Fardamento', 'Fardamento'), ('Diversos', 'Diversos')], max_length=30, verbose_name='Tipo de material')),
                ('descricao', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Descrição')),
                ('quantidade_total', models.IntegerField(default=1, help_text='Total físico existente no almoxarifado.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade total')),
                ('quantidade_disponivel', models.IntegerField(default=1, help_text='Total disponível para acautelar (total − acautelados).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade disponível')),
                ('condicao', models.CharField(choices=[('Novo', 'Novo'), ('Bom', 'Bom'), ('Precisa de Manutenção', 'Precisa de Manutenção'), ('Inservível', 'Inservível')], default='Bom', max_length=30, verbose_name='Condição')),
                ('localizacao', models.CharField(blank=True, help_text='Ex: Prateleira A3, Armário 2.', max_length=100, null=True, verbose_name='Localização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Item',
                'verbose_name_plural': 'historical Itens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, db_index=True, help_text='Preencha apenas para itens individualizados (armas, rádios). Deixe vazio para itens de lote (munição, fardamento).', max_length=100, null=True, unique=True, verbose_name='Número de série')),
                ('tipo_material', models.CharField(choices=[('Armamento', 'Armamento'), ('Munição', 'Munição'), ('Colete Balístico', 'Colete Balístico'), ('Rádio HT', 'Rádio HT'), ('Viatura', 'Viatura'), ('Fardamento', 'Fardamento'), ('Diversos', 'Diversos')], max_length=30, verbose_name='Tipo de material')),
                ('descricao', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Descrição')),
                ('quantidade_total', models.IntegerField(default=1, help_text='Total físico existente no almoxarifado.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade total')),
                ('quantidade_disponivel', models.IntegerField(default=1, help_text='Total disponível para acautelar (total − acautelados).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade disponível')),
                ('condicao', models.CharField(choices=[('Novo', 'Novo'), ('Bom', 'Bom'), ('Precisa de Manutenção', 'Precisa de Manutenção'), ('Inservível', 'Inservível')], default='Bom', max_length=30, verbose_name='Condição')),
                ('localizacao', models.CharField(blank=True, help_text='Ex: Prateleira A3, Armário 2.', max_length=100, null=True, verbose_name='Localização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['tipo_material', 'descricao'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade_disponivel__lte', models.F('quantidade_total'))), name='item_disponivel_lte_total'), models.CheckConstraint(condition=models.Q(('quantidade_total__gte', 0)), name='item_total_gte_zero'), models.CheckConstraint(condition=models.Q(('quantidade_disponivel__gte', 0)), name='item_disponivel_gte_zero')],
            },
        ),
    ]
