# Generated by Django 6.0.5 on 2026-05-09 03:10

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Matrícula / RG PM')),
                ('nome_guerra', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome de guerra')),
                ('nome_completo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome completo')),
                ('posto_graduacao', models.CharField(choices=[('Sd', 'Soldado'), ('Cb', 'Cabo'), ('Sgt', 'Sargento'), ('Sub Ten', 'Subtenente'), ('Ten', 'Tenente'), ('Cap', 'Capitão'), ('Maj', 'Major'), ('TC', 'Tenente-Coronel'), ('Cel', 'Coronel')], max_length=20, verbose_name='Posto / Graduação')),
                ('companhia_pelotao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Companhia / Pelotão')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Férias', 'Férias'), ('Licença', 'Licença'), ('Inativo', 'Inativo')], default='Ativo', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Policial',
                'verbose_name_plural': 'Policiais',
                'ordering': ['nome_guerra'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPolicial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('matricula', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Matrícula / RG PM')),
                ('nome_guerra', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome de guerra')),
                ('nome_completo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome completo')),
                ('posto_graduacao', models.CharField(choices=[('Sd', 'Soldado'), ('Cb', 'Cabo'), ('Sgt', 'Sargento'), ('Sub Ten', 'Subtenente'), ('Ten', 'Tenente'), ('Cap', 'Capitão'), ('Maj', 'Major'), ('TC', 'Tenente-Coronel'), ('Cel', 'Coronel')], max_length=20, verbose_name='Posto / Graduação')),
                ('companhia_pelotao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Companhia / Pelotão')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Férias', 'Férias'), ('Licença', 'Licença'), ('Inativo', 'Inativo')], default='Ativo', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Policial',
                'verbose_name_plural': 'historical Policiais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
