# Generated by Django 6.0.5 on 2026-05-09 03:10

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cautela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade retirada. Mínimo 1.', verbose_name='Quantidade')),
                ('data_retirada', models.DateTimeField(auto_now_add=True, verbose_name='Data de retirada')),
                ('data_devolucao_prevista', models.DateTimeField(blank=True, null=True, verbose_name='Prev. devolução')),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True, verbose_name='Devolução real')),
                ('responsavel_entrega', models.CharField(max_length=100, verbose_name='Responsável pela entrega')),
                ('status', models.CharField(choices=[('Ativa', 'Ativa'), ('Devolvida', 'Devolvida')], db_index=True, default='Ativa', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Cautela',
                'verbose_name_plural': 'Cautelas',
                'ordering': ['-data_retirada'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCautela',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade retirada. Mínimo 1.', verbose_name='Quantidade')),
                ('data_retirada', models.DateTimeField(blank=True, editable=False, verbose_name='Data de retirada')),
                ('data_devolucao_prevista', models.DateTimeField(blank=True, null=True, verbose_name='Prev. devolução')),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True, verbose_name='Devolução real')),
                ('responsavel_entrega', models.CharField(max_length=100, verbose_name='Responsável pela entrega')),
                ('status', models.CharField(choices=[('Ativa', 'Ativa'), ('Devolvida', 'Devolvida')], db_index=True, default='Ativa', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Cautela',
                'verbose_name_plural': 'historical Cautelas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
