# Generated by Django 6.0.5 on 2026-05-09 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cautelas', '0001_initial'),
        ('efetivo', '0001_initial'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cautela',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cautelas', to='estoque.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='cautela',
            name='policial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cautelas', to='efetivo.policial', verbose_name='Policial'),
        ),
        migrations.AddField(
            model_name='historicalcautela',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcautela',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estoque.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='historicalcautela',
            name='policial',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='efetivo.policial', verbose_name='Policial'),
        ),
        migrations.AddIndex(
            model_name='cautela',
            index=models.Index(fields=['policial', 'status'], name='cautela_policial_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cautela',
            index=models.Index(fields=['item', 'status'], name='cautela_item_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cautela',
            index=models.Index(fields=['status', 'data_devolucao_prevista'], name='cautela_atraso_idx'),
        ),
    ]
