# Generated by Django 6.0.5 on 2026-05-09 03:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('papel', models.CharField(choices=[('admin', 'Administrador (Oficial)'), ('operador', 'Operador (Sgt / Almoxarife)'), ('leitura', 'Consulta (Sd / Cb)')], default='leitura', help_text='Define o nível de permissão no sistema.', max_length=20, verbose_name='Papel de acesso')),
                ('unidade', models.CharField(blank=True, default='', help_text='Ex: 1ª CIA, 2º PEL. Usado para controle futuro de acesso por setor.', max_length=50, verbose_name='Unidade / Companhia')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário PM',
                'verbose_name_plural': 'Usuários PM',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criar_cautela', 'Criar Cautela'), ('devolver_item', 'Devolver Item'), ('criar_item', 'Criar Item'), ('alterar_item', 'Alterar Item'), ('deletar_item', 'Deletar Item'), ('criar_policial', 'Criar Policial'), ('alterar_policial', 'Alterar Policial'), ('deletar_policial', 'Deletar Policial'), ('alterar_senha', 'Alterar Senha'), ('criar_usuario', 'Criar Usuário'), ('deletar_usuario', 'Deletar Usuário')], db_index=True, max_length=50, verbose_name='Ação')),
                ('tabela_afetada', models.CharField(db_index=True, max_length=50, verbose_name='Tabela afetada')),
                ('registro_id', models.PositiveIntegerField(db_index=True, verbose_name='ID do registro afetado')),
                ('dados_anteriores', models.TextField(blank=True, null=True, verbose_name='Snapshot anterior (JSON)')),
                ('dados_novos', models.TextField(blank=True, null=True, verbose_name='Snapshot posterior (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent')),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/hora UTC')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalUsuarioPM',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('papel', models.CharField(choices=[('admin', 'Administrador (Oficial)'), ('operador', 'Operador (Sgt / Almoxarife)'), ('leitura', 'Consulta (Sd / Cb)')], default='leitura', help_text='Define o nível de permissão no sistema.', max_length=20, verbose_name='Papel de acesso')),
                ('unidade', models.CharField(blank=True, default='', help_text='Ex: 1ª CIA, 2º PEL. Usado para controle futuro de acesso por setor.', max_length=50, verbose_name='Unidade / Companhia')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuário PM',
                'verbose_name_plural': 'historical Usuários PM',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
